apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
  namespace: openshift-observability
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tempostack-traces-write-audit
rules:
  - apiGroups:
      - tempo.grafana.com
    resources:
      - audit
    resourceNames:
      - traces
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-ingest-traces-write
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tempostack-traces-write-audit
subjects:
  - kind: ServiceAccount
    name: otel-collector
    namespace: openshift-observability
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lokistack-logs-write-audit
rules:
  - apiGroups:
      - loki.grafana.com
    resources:
      - audit
    resourceNames:
      - logs
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-ingest-logs-write
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lokistack-logs-write-audit
subjects:
  - kind: ServiceAccount
    name: otel-collector
    namespace: openshift-observability
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: ingest
  namespace: openshift-observability
spec:
  mode: deployment
  serviceAccount: otel-collector
  config:
    extensions:
      bearertokenauth:
        filename: /var/run/secrets/kubernetes.io/serviceaccount/token
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      resource/loki:
        attributes:
          - key: kubernetes.namespace_name
            from_attribute: k8s.namespace.name
            action: upsert
          - key: kubernetes.pod_name
            from_attribute: k8s.pod.name
            action: upsert
          - key: kubernetes.container_name
            from_attribute: k8s.container.name
            action: upsert
          - key: log_type
            value: audit
            action: upsert
      transform/loki:
        log_statements:
          - context: log
            statements:
              - set(attributes["level"], ConvertCase(severity_text, "lower"))
          - context: log
            statements:
              - set(attributes["message"], body)
    exporters:
      debug:
        verbosity: detailed
      otlp/tempo:
        endpoint: tempo-tracing-gateway.openshift-tracing.svc.cluster.local:8090
        tls:
          insecure: false
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        auth:
          authenticator: bearertokenauth
        headers:
          X-Scope-OrgID: audit
      otlphttp/lokistack:
        endpoint: https://logging-loki-gateway-http.openshift-logging.svc.cluster.local:8080/api/logs/v1/audit/otlp
        tls:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        auth:
          authenticator: bearertokenauth
    service:
      extensions: [bearertokenauth]
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [debug, otlp/tempo]
        logs:
          receivers: [otlp]
          processors: [resource/loki, transform/loki]
          exporters: [debug, otlphttp/lokistack]
