apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  name: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  type: Monitoring
  monitoring:
    perses:
      enabled: true
