apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  managementState: Managed
  size: 1x.demo
  storage:
    schemas:
      - effectiveDate: "2025-10-07"
        version: v13
    secret:
      name: logging-loki-s3
      type: s3
  storageClassName: gp3-csi
  limits:
    global:
      retention:
        days: 7
  tenants:
    mode: openshift-logging
